### ISSUE TITLE
Misalignment of Skills in the Imagination View - and Wrong Icon?

### ISSUE THREAD

**Issue by hawkwell** [ChildrenOfUr/cou-issues#1607]
In the skills list of the Imagination view the penpersonship skill has misaligned text overlapping the tinkering skill. Also both skills have the same brain icon, which is not the icon of either in the encyclopedia

![screenshot 2016-09-03 07 57 32](https://cloud.githubusercontent.com/assets/20943965/18223336/1efd6dfc-71ac-11e6-95d1-2f485c3f6976.png)

**Comment by ElleLament** [comment]
@hawkwell Do you still see it that way after reloading?

**Comment by hawkwell** [comment]
@ElleLament After reloading, after a fresh login - it's been that way for
days (weeks?), I just got around to mentioning it.

**Comment by babi1** [comment]
Penpersonship overlays Alchemy too, now I see you haven't started yet A1 but P1 overlay also Alchemy.
The icon hmm.... we had since we introduced the Learning SKill the brain and the tank meter for showing the learning status, same icon for all Skills
Imho the brain icon is ok but yes Penpersonship overlay the next skill one is learning and I add, once the Skill is complete still overlays the nearby Skill.

**Comment by Klikini** [comment]
Oh, CSS, how I hate you.

I think I just need to decrease the font size of the skill names a tiny bit.
