### ISSUE TITLE
I cannot log into Children of Ur

### ISSUE THREAD

**Issue by JenPaul1428** [ChildrenOfUr/cou-issues#820]
I signed on with my gmail account.  When asked 'What do you want to be called?" I try typing in my old avatar name from glitch, Falafel Princess, however it will only let me enter in the first part of the name.  When I copy and past my avatar name in my avatar image comes up, but "that's totally me" nothing happens.  Also, it's says at the top "it's good to see you Falafel Princess" AND its says "Hey look a new face".

Thank you for any help you can provide.

**Comment by RobertBlackhart** [comment]
I see 2 users in the database with a username like Falafel:

id  |     username     |           email           | bio |     registration_date      | username_color | chat_disabled |                achievements                 |         last_login         | elevation 
------+------------------+---------------------------+-----+----------------------------+----------------+---------------+---------------------------------------------+----------------------------+-----------
 1236 | Falafel Princess | _[redacted]_     |     | 2015-04-20 23:20:01.99807  | #              | f             | []                                          |                            | 
 3936 | Falafel          | _[redacted]_ |     | 2016-05-04 00:45:49.077422 | #              | f             | ["junior_ok_explorer","senior_ok_explorer"] | 2016-05-12 01:04:56.628421 | 
(2 rows)

The user Falafel Princess registered a few weeks ago but has never logged in. The user Falafel registered a few days ago and last logged in today. Was it the case that you want to use the username "Falafel Princess" on the account that is currently labeled "Falafel"?

Also, they are both under different email addresses (because that must be unique). Can you tell me which you want to use (just give me the domain and I can figure out which one is right)?

**Comment by JenPaul1428** [comment]
Both are me.  I tried repeatedly to log in as Falafel Princess but could
not, however I had no problem logging in as Falafel.  I want to go as my
old avatar Falafel Princess.

Thank You.

Jennifer Paul

**Comment by RobertBlackhart** [comment]
I updated your stuff in the database. You may need to log out and log back in for it to take effect, but you should be able to log into the game as you have been and your username will be changed to Falafel Princess.

Please let me know if you have any issues. I'll leave the bug report open for another few days to let you try it out.
